name: note-paper
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy=1.22.3
  - pandas=1.4.2
  - psutil=5.9.0
  - python=3.9.12
  - scikit-learn
  - tensorflow=2.7.0
  - termcolor=1.1.0
  - wandb=0.12.14
